name: Tests

on: [pull_request]

jobs:
    test:
        runs-on: [ubuntu-latest]

        strategy:
            matrix:
                node-version: [18.x]
        
        steps:
            - uses: actions/checkout@v2
            - name: Use Node ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                node-version: ${{matrix.node-version}}
            - name: npm install
              run: npm ci # same as npm install
            - name: run tests
              run: npm test
